/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsltimeloggingsystem;

import com.digitalpersona.uareu.Fmd;
import com.digitalpersona.uareu.Reader;
import com.digitalpersona.uareu.ReaderCollection;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author L R E
 */
public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployee
     */
    private int employeeID;
    private ReaderCollection m_collection;
    private Reader m_reader;
    private Fmd fmd;
    private static User sessionUser = null;
    private static User user;
    private static ArrayList<String> employeePages = new ArrayList<>();
    private final JPanel panel = new JPanel();
    public void RestrictViews(ArrayList<String> employeePages){
        if(!sessionUser.getRole().equals("Administrator")){
            btnEditEmployee.setVisible(false);
            btnDeleteEmployee.setVisible(false);
            for(int i = 0; i < employeePages.size(); i++){
                if(Pattern.compile(Pattern.quote(employeePages.get(i)), Pattern.CASE_INSENSITIVE).matcher("btnEditEmployee").find()){
                   btnEditEmployee.setVisible(true);
                }
                if(Pattern.compile(Pattern.quote(employeePages.get(i)), Pattern.CASE_INSENSITIVE).matcher("btnDeleteEmployee").find()){
                   btnDeleteEmployee.setVisible(true);
                }
            }
        }
        
        
    }
    private static DefaultTableModel FillTableNotes(int employeeID) throws ClassNotFoundException, SQLException {
        DefaultTableModel model = new DefaultTableModel();
        
        List<Notes> notes = new ArrayList<Notes>();
        notes = DB.getNotes(employeeID);
        
        model.addColumn("Note ID");
        model.addColumn("Employee ID");
        model.addColumn("Name");
        model.addColumn("Notes");
        model.addColumn("Note Date");
        int notesCount = notes.size();
        for(int i = 0; i < notesCount; i++){
            Object [] rowData = {notes.get(i).getNoteID(), notes.get(i).getEmployeeID(), notes.get(i).getFirstName() +" " + notes.get(i).getLastName(), notes.get(i).getNote(), notes.get(i).getNoteDate()};
            model.addRow(rowData);
        }
       
        return model;
    }
    private static DefaultTableModel FillTableFiles(int employeeID) throws ClassNotFoundException, SQLException, IOException {
        DefaultTableModel model = new DefaultTableModel();
        
        List<Files> files = new ArrayList<Files>();
        files = DB.getFiles(employeeID);
        
        model.addColumn("Note ID");
        model.addColumn("Employee ID");
        model.addColumn("Name");
        model.addColumn("File Name");
        model.addColumn("File Date");
        for(int i = 0; i < files.size(); i++){
            Object [] rowData = {files.get(i).getFileID(),files.get(i).getEmployeeID(), files.get(i).getFirstName() +" " + files.get(i).getLastName(), files.get(i).getFileName(), files.get(i).getUploadDate()};
            model.addRow(rowData);
        }
       
        return model;
//        new jTable1.setModel(model);
    }
    public EditEmployee(User user, ArrayList<String> employeePages) throws ClassNotFoundException, SQLException, ParseException {
        
        initComponents();

        this.sessionUser = user;
        this.employeePages = employeePages;
        RestrictViews(this.employeePages);
        DB.setUserLogStatus(user.getEmployeeID(),"Page Visit", "Edit Employee");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTimeIn = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSSSNumber = new javax.swing.JTextField();
        txtTinNumber = new javax.swing.JTextField();
        txtPagibigNumber = new javax.swing.JTextField();
        txtTimeOut = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSSSDeduction = new javax.swing.JTextField();
        txtPhilHealthDeduction = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        txtTaxDeduction = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPhilHealth = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMemos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtLates = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAbsences = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jCheckboxAddEmployee = new javax.swing.JCheckBox();
        jCheckboxEditEmployee = new javax.swing.JCheckBox();
        jCheckboxDeleteEmployee = new javax.swing.JCheckBox();
        jCheckBoxPayroll = new javax.swing.JCheckBox();
        jCheckBoxClaimSalary = new javax.swing.JCheckBox();
        jCheckboxReports = new javax.swing.JCheckBox();
        jCheckBoxUpload = new javax.swing.JCheckBox();
        btnEditEmployee = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtPagibigDeduction = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnAddNote = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnUploadFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFiles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Last Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Telephone No.:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Home Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Time In:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Employee No.:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Mobile No.:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Time Out:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Rate/Day:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("SSS No.:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Tin No.:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Pag-Ibig No.:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("SSS Deduction:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("PhilHealth Deduction:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Tax Deduction:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("PhilHealth No.:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("No. Of Memo:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setText("No. Of Late:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setText("No. Of Absences");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Access:");

        jCheckboxAddEmployee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckboxAddEmployee.setText("Add Employee");

        jCheckboxEditEmployee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckboxEditEmployee.setText("Edit Employee");

        jCheckboxDeleteEmployee.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckboxDeleteEmployee.setText("Delete Employee");

        jCheckBoxPayroll.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxPayroll.setText("Salary Overview");
        jCheckBoxPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPayrollActionPerformed(evt);
            }
        });

        jCheckBoxClaimSalary.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxClaimSalary.setText("Salary Claim");

        jCheckboxReports.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckboxReports.setText("Reports");

        jCheckBoxUpload.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxUpload.setText("Upload File");

        btnEditEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditEmployee.setText("Update");
        btnEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmployeeActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteEmployee.setText("Delete");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Pag-ibig Deduction:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setText("Emergency Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtPagibigNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMemos)))
                        .addGap(543, 543, 543))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelephoneNumber))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(79, 79, 79)
                                .addComponent(jLabel22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtTinNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(txtSSSNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTimeIn, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(68, 68, 68)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel14)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel20)
                                                                .addGap(25, 25, 25)))
                                                        .addGap(18, 18, 18))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel16)
                                                            .addComponent(jLabel15))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtSSSDeduction, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                    .addComponent(txtPhilHealthDeduction)
                                                    .addComponent(txtLates, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPagibigDeduction, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTaxDeduction)
                                                    .addComponent(txtPhilHealth)
                                                    .addComponent(txtRate, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAbsences, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPassword)))))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckboxAddEmployee)
                    .addComponent(jCheckboxEditEmployee)
                    .addComponent(jCheckboxDeleteEmployee)
                    .addComponent(jCheckBoxPayroll)
                    .addComponent(jCheckBoxClaimSalary)
                    .addComponent(jCheckboxReports)
                    .addComponent(jCheckBoxUpload))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnEditEmployee)
                .addGap(95, 95, 95)
                .addComponent(btnDeleteEmployee)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jCheckboxAddEmployee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckboxEditEmployee)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(txtTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSSSNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtSSSDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtTaxDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhilHealthDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtPagibigNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(txtAbsences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPagibigDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtMemos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtLates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jCheckboxDeleteEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxPayroll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxClaimSalary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckboxReports)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxUpload)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEmployee)
                    .addComponent(btnEditEmployee)
                    .addComponent(jButton3))
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Employee Profile", jPanel1);

        btnAddNote.setText("Add Note");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        jTableNotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Note", "Created By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNotesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNotes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddNote)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notes", jPanel2);

        btnUploadFile.setText("Upload");
        btnUploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFileActionPerformed(evt);
            }
        });

        jTableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "File", "Type", "Uploader"
            }
        ));
        jScrollPane2.setViewportView(jTableFiles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnUploadFile)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUploadFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Attached Files", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPayrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPayrollActionPerformed

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            AddNote note = new AddNote(this.sessionUser, "Employees", this.employeePages);
            note.setTitle("DSL Time Logging | Add Note");
            note.pack();
            note.setLocationRelativeTo(null);
            note.setDefaultCloseOperation(0);
            note.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        // TODO add your handling code here:
        String role = "";
        String status = "";
        
        role = sessionUser.getRole();
        
        if(role.equals("Administrator")){
            try {
                System.out.println(employeeID);
                status = DB.deleteUser(employeeID);
                if(status.equals("Successful")){
                    JOptionPane.showMessageDialog(panel, "Delete Employee Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    EmployeesUI eUI;
                    try {
                        eUI = new EmployeesUI(this.sessionUser, this.employeePages);
                        eUI.setTitle("DSL Time Logging | Employees");
                        eUI.pack();
                        eUI.setLocationRelativeTo(null);
                        eUI.setDefaultCloseOperation(0);
                        eUI.setVisible(true);
                        DB.setUserLogStatus(sessionUser.getEmployeeID(),"Save", "Delete User");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ParseException ex) {
                        Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(panel, "System Error. Please contact Administrator", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(panel, "You are not authorized to make changes. Please contact administrator", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        try {
            // TODO add your handling code here:
            EmployeesUI eUI = new EmployeesUI(this.sessionUser, this.employeePages);
            eUI.setTitle("DSL Time Logging | Employees");
            eUI.pack();
            eUI.setLocationRelativeTo(null);
            eUI.setDefaultCloseOperation(0);
            eUI.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNotesMouseClicked
        // TODO add your handling code here:
        int row = jTableNotes.rowAtPoint(evt.getPoint());
        int employeeID = (int) jTableNotes.getValueAt(row, 1);
        int noteID = (int) jTableNotes.getValueAt(row,0);
            
        this.setVisible(false);
        try {
            ViewNotes viewNotes = new ViewNotes(this.sessionUser, this.employeePages, employeeID, noteID);
            
            viewNotes.setTitle("DSL Time Logging | View Notes");
            viewNotes.pack();
            viewNotes.setLocationRelativeTo(null);
            viewNotes.setDefaultCloseOperation(0);
            viewNotes.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeesUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeesUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EmployeesUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableNotesMouseClicked

    private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFileActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            UploadDocuments upload = new UploadDocuments(this.sessionUser, "Employees", this.employeePages);
            upload.setTitle("DSL Time Logging | Upload File");
            upload.pack();
            upload.setLocationRelativeTo(null);
            upload.setDefaultCloseOperation(0);
            upload.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUploadFileActionPerformed

    private void btnEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmployeeActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String role = sessionUser.getRole();
        String status = "";
        if(role.equals("Administrator")){
            try {
                int employeeID = 0;
        
                float SSSDeduction = 0;
                float pagibigDeduction = 0;
                float philHealthDeduction = 0;
                float rate = 0;
                float taxDeduction = 0;
                int noLates = 0;
                int noMemos = 0;
                int noAbsences = 0;
                try{
                    employeeID = Integer.parseInt(txtEmployeeID.getText());

                    SSSDeduction = Float.parseFloat(txtSSSDeduction.getText());
                    pagibigDeduction = Float.parseFloat(txtPagibigDeduction.getText());
                    philHealthDeduction = Float.parseFloat(txtPhilHealthDeduction.getText());
                    rate = Float.parseFloat(txtRate.getText());
                    taxDeduction = Float.parseFloat(txtTaxDeduction.getText());
                    noLates = Integer.parseInt(txtLates.getText());
                    noMemos = Integer.parseInt(txtMemos.getText());
                    noAbsences = Integer.parseInt(txtAbsences.getText());
                }catch(NumberFormatException e){
                }

                String address = txtAddress.getText();
                String firstName = txtFirstName.getText();
                String lastName = txtLastName.getText();
                String timeIn = txtTimeIn.getText();
                String timeOut = txtTimeOut.getText();
                String SSSNumber = txtSSSNumber.getText();
                String philHealthNumber = txtPhilHealth.getText();
                String pagibigNumber = txtPagibigNumber.getText();
                String tinNumber = txtTinNumber.getText();
                String telephoneNumber = txtTelephoneNumber.getText();
                String mobileNumber = txtMobileNumber.getText();
                String password = String.valueOf(txtPassword.getPassword());
                byte[] fingerPrintImage = user.getFingerPrintImage();
                if(fingerPrintImage == null || address.equals("") || firstName.equals("") || lastName.equals("") || timeIn.equals("") || timeOut.equals("") || role.equals("") || employeeID == 0 || rate == 0 || password.equals("")){
                    JOptionPane.showMessageDialog(panel, "Please complete fields before proceeding", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    status = DB.updateUser(firstName, lastName, employeeID, address, telephoneNumber, mobileNumber, rate, timeIn, timeOut, SSSNumber, 
                            philHealthNumber, tinNumber, pagibigNumber, SSSDeduction, pagibigDeduction, philHealthDeduction, taxDeduction,
                            password, noLates, noMemos, noAbsences);
                    if(status.equals("Successful")){
                        JOptionPane.showMessageDialog(panel, "Edit Employee Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                        EmployeesUI eUI;
                        try {
                            eUI = new EmployeesUI(this.sessionUser, this.employeePages);
                            eUI.setTitle("DSL Time Logging | Employees");
                            eUI.pack();
                            eUI.setLocationRelativeTo(null);
                            eUI.setDefaultCloseOperation(0);
                            eUI.setVisible(true);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ParseException ex) {
                            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
                            try {
                                DB.setUserLogStatus(sessionUser.getEmployeeID(),"Save", "Update User");
                            } catch (ParseException ex1) {
                                Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex1);
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(panel, "System Error. Please contact Administrator", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(panel, "You are not authorized to make changes. Please contact administrator", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setEditableFields(int employeeID) throws ClassNotFoundException, SQLException, IOException{
        this.employeeID = employeeID;
        this.user =  DB.getUserDetails(employeeID);
        DefaultTableModel modelNotes = this.FillTableNotes(this.employeeID);
        jTableNotes.setModel(modelNotes);
        DefaultTableModel modelFiles = this.FillTableFiles(this.employeeID);
        jTableFiles.setModel(modelFiles);
        
        txtEmployeeID.setText(Integer.toString(user.getEmployeeID()));
        txtFirstName.setText(user.getFirstName());
        txtLastName.setText(user.getLastName());
        txtMobileNumber.setText(user.getMobileNumber());
        txtTelephoneNumber.setText(user.getTelephoneNumber());
        txtAddress.setText(user.getAddress());
        txtRate.setText(Float.toString(user.getRate()));
        txtTimeIn.setText(user.getTimeIn());
        txtTimeOut.setText(user.getTimeOut());
        //getRole()
        txtSSSNumber.setText(user.getSSSNumber());
        txtPhilHealth.setText(user.getPhilHealthNumber());
        txtPagibigNumber.setText(user.getPagibigNumber());
        txtTinNumber.setText(user.getTinNumber());
        txtSSSDeduction.setText(Float.toString(user.getSSSDeduction()));
        txtPagibigDeduction.setText(Float.toString(user.getPagibigDeduction()));
        txtPhilHealthDeduction.setText(Float.toString(user.getPhilHealthDeduction()));
        txtTaxDeduction.setText(Float.toString(user.getTaxDeduction()));
        txtPassword.setText(user.getPassword());
        txtMemos.setText(Integer.toString(user.getNoMemos()));
        txtLates.setText(Integer.toString(user.getNoLates()));
        txtAbsences.setText(Integer.toString(user.getNoAbsences()));
    }
//    private void btnEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                                
//        
//        
//    }                                               
//
//    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        // TODO add your handling code here:
//        EmployeesUI eUI;
//        try {
//            this.setVisible(false);
//            eUI = new EmployeesUI(this.sessionUser, this.employeePages);
//            eUI.setTitle("DSL Time Logging | Employees");
//            eUI.pack();
//            eUI.setLocationRelativeTo(null);
//            eUI.setDefaultCloseOperation(0);
//            eUI.setVisible(true);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ParseException ex) {
//            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }                                              
//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnEditEmployee;
    private javax.swing.JButton btnUploadFile;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxClaimSalary;
    private javax.swing.JCheckBox jCheckBoxPayroll;
    private javax.swing.JCheckBox jCheckBoxUpload;
    private javax.swing.JCheckBox jCheckboxAddEmployee;
    private javax.swing.JCheckBox jCheckboxDeleteEmployee;
    private javax.swing.JCheckBox jCheckboxEditEmployee;
    private javax.swing.JCheckBox jCheckboxReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFiles;
    private javax.swing.JTable jTableNotes;
    private javax.swing.JTextField txtAbsences;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLates;
    private javax.swing.JTextField txtMemos;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtPagibigDeduction;
    private javax.swing.JTextField txtPagibigNumber;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhilHealth;
    private javax.swing.JTextField txtPhilHealthDeduction;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSSSDeduction;
    private javax.swing.JTextField txtSSSNumber;
    private javax.swing.JTextField txtTaxDeduction;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtTimeIn;
    private javax.swing.JTextField txtTimeOut;
    private javax.swing.JTextField txtTinNumber;
    // End of variables declaration//GEN-END:variables
}
