package dsltimeloggingsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Menu extends javax.swing.JFrame {
    
    private static int sessionEmployeeID = 0;
    /**
     * Creates new form Menu
     */
//    public Menu() {
//        initComponents();
//    }
    
    public Menu(int employeeID) throws ClassNotFoundException, SQLException{
        initComponents();
        this.sessionEmployeeID = employeeID;
        System.out.println("Menu " + employeeID);
        this.filterView(employeeID);
    }
    public void filterView(int employeeID) throws ClassNotFoundException, SQLException{
        User user = DB.getUserDetails(employeeID);
        if(user.getRole().equals("Administrator")){
            btnEmployee.setVisible(true);
            btnClaimSalary.setVisible(true);
            btnReports.setVisible(true);
            btnPayroll.setVisible(true);
            btnSalaryCondition.setVisible(true);
        }
        else if(user.getRole().equals("Payroll")){
            btnEmployee.setVisible(false);
            btnClaimSalary.setVisible(false);
            btnReports.setVisible(false);
            btnPayroll.setVisible(true);
            btnSalaryCondition.setVisible(true);
        }
        else{
            btnEmployee.setVisible(false);
            btnClaimSalary.setVisible(false);
            btnReports.setVisible(false);
            btnPayroll.setVisible(false);
            btnSalaryCondition.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JButton();
        btnPayroll = new javax.swing.JButton();
        btnClaimSalary = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSalaryCondition = new javax.swing.JToggleButton();
        btnHome = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        btnEmployee.setText("Employee");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnPayroll.setText("Payroll Overview");
        btnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollActionPerformed(evt);
            }
        });

        btnClaimSalary.setText("Claim Salary");
        btnClaimSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimSalaryActionPerformed(evt);
            }
        });

        btnReports.setText("Reports");

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSalaryCondition.setText("Add Salary Condition");
        btnSalaryCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryConditionActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalaryCondition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClaimSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnEmployee)
                .addGap(16, 16, 16)
                .addComponent(btnPayroll)
                .addGap(18, 18, 18)
                .addComponent(btnClaimSalary)
                .addGap(18, 18, 18)
                .addComponent(btnSalaryCondition)
                .addGap(18, 18, 18)
                .addComponent(btnReports)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            EmployeesUI eUI = new EmployeesUI(this.sessionEmployeeID);
            eUI.setTitle("DSL Time Logging | Employees");
            eUI.pack();
            eUI.setLocationRelativeTo(null);
            eUI.setDefaultCloseOperation(0);
            eUI.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Payroll payroll = new Payroll(this.sessionEmployeeID);
        payroll.setTitle("DSL Time Logging | Payroll");
        payroll.pack();
        payroll.setLocationRelativeTo(null);
        payroll.setDefaultCloseOperation(0);
        payroll.setVisible(true);
    }//GEN-LAST:event_btnPayrollActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home home;
        try {
            home = new Home(this.sessionEmployeeID);
            home.setTitle("DSL Time Logging | Home");
            home.pack();
            home.setLocationRelativeTo(null);
            home.setDefaultCloseOperation(0);
            home.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnClaimSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimSalaryActionPerformed
        try {
            // TODO add your handling code here:
            EmployeeList list = new EmployeeList(this.sessionEmployeeID);
            list.setTitle("DSL Time Logging | List of Emoloyees");
            list.pack();
            list.setLocationRelativeTo(null);
            list.setDefaultCloseOperation(0);
            list.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClaimSalaryActionPerformed

    private void btnSalaryConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryConditionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SalaryCondition condition = new SalaryCondition(this.sessionEmployeeID);
        condition.setTitle("DSL Time Logging | Salary Condition");
        condition.pack();
        condition.setLocationRelativeTo(null);
        condition.setDefaultCloseOperation(0);
        condition.setVisible(true);
    }//GEN-LAST:event_btnSalaryConditionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaimSalary;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JToggleButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayroll;
    private javax.swing.JButton btnReports;
    private javax.swing.JToggleButton btnSalaryCondition;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
