/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsltimeloggingsystem;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author L R E
 */
public class SystemLogs extends javax.swing.JFrame {

    /**
     * Creates new form SystemLogs
     */
    private static User sessionUser = null;
    private static int temp = 0;
    private static ArrayList<String> employeePages = new ArrayList<String>();
    public SystemLogs(User user, ArrayList<String> employeePages) throws ClassNotFoundException, SQLException, ParseException {
        List<UserLogs> userlogs = null;
        initComponents();
        this.sessionUser = user;
        this.employeePages = employeePages;
        DB.setUserLogStatus(user.getEmployeeID(),"Page Visit", "System Logs");
        DefaultTableModel model = SystemLogs.FillTable();
        jTable1.setModel(model);
    }
    
    public static DefaultTableModel FillTable() throws ClassNotFoundException, SQLException, ParseException{
        int i = 0;
        List<UserLogs> logs = new ArrayList<UserLogs>();
        logs = FilterSystemLogs.getUserLogs();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Employee ID");
        model.addColumn("Employee Name");
        model.addColumn("Access Type");
        model.addColumn("Access Location");
        model.addColumn("Access Time");
        if(logs == null){
            logs = DB.getSystemLogs(0, "", "", "");
        }
        if(logs != null){
            for(i = 0; i < logs.size(); i++){
                Object [] rowData = {logs.get(i).getEmployeeID(), logs.get(i).getEmployeeName(), logs.get(i).getType(), logs.get(i).getLogDetails(), 
                    logs.get(i).getLogDate()};
                model.addRow(rowData);
            }
        }
        return model;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMainMenu = new javax.swing.JButton();
        btnAddFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMainMenu.setText("Main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        btnAddFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddFilter.setText("Add Filter");
        btnAddFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnMainMenu)
                .addGap(18, 18, 18)
                .addComponent(btnAddFilter)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu)
                    .addComponent(btnAddFilter))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu;
        try {
            menu = new Menu(this.sessionUser, this.employeePages);
            menu.setTitle("DSL Time Logging | Menu");
            menu.pack();
            menu.setLocationRelativeTo(null);
            menu.setDefaultCloseOperation(0);
            menu.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SalaryCondition.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnAddFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilterActionPerformed
        try {
            // TODO add your handling code here:
            FilterSystemLogs filter;
            this.setVisible(false);
            filter = new FilterSystemLogs(this.sessionUser, this.employeePages);
            filter.setTitle("DSL Time Logging | Filter System Logs");
            filter.pack();
            filter.setLocationRelativeTo(null);
            filter.setDefaultCloseOperation(0);
            filter.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(SystemLogs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemLogs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SystemLogs.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAddFilterActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFilter;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
